### ISSUE TITLE
Naive modification of selected date fails to update the DateChooser display 

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#28] opened 2017-10-13 05:55 UTC
If you get a reference to the selected data and modify it the display doesn't update even if you try and force it to update.

Sample screen shot
![2017-10-13_16-46-49](https://user-images.githubusercontent.com/144504/31532043-9ccb2b1a-b036-11e7-91b4-7aff5f662a76.png)

Sample code to reproduce this.
```
<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:js="library://ns.apache.org/flexjs/basic" xmlns:beads="org.apache.flex.html.beads.*">

    <js:valuesImpl>
        <js:SimpleCSSValuesImpl/>
    </js:valuesImpl>

    <fx:Script>
        <![CDATA[
        import org.apache.flex.html.beads.DateChooserView;

        public function tomorrow():void {
            var tomorrow:Date =  chooser.selectedDate;
            tomorrow.setDate(tomorrow.getDate() + 1); // fails to update display
            chooser.selectedDate = tomorrow; // trying to force it also fails to update display
            date.text = chooser.selectedDate.toDateString(); // displays tomorrow's date so display is out of sync with selected date
        }
        ]]>
    </fx:Script>

    <js:beads>

    </js:beads>

    <js:initialView>
        <js:View>
            <js:Group id="content">
                <js:beads>
                    <js:VerticalLayout />
                </js:beads>
                <js:DateChooser id="chooser" width="300" />

                <js:TextButton text="Set Date" click="tomorrow()"/>
                <js:Label id="date" />
            </js:Group>
        </js:View>
    </js:initialView>

</js:Application>
```

This can be worked around by making a new date based on the existing selected date but seem a little cumbersome and error prone.

```
        public function tomorrow():void {
            var tomorrow:Date =  new Date(chooser.selectedDate.getTime());
            tomorrow.setDate(tomorrow.getDate() + 1);
            chooser.selectedDate = tomorrow;
            date.text = chooser.selectedDate.toDateString();
        }
```

Perhaps it would be a good idea to expose a method to update the display to keep it in sync with changes to the selected date so you could write something like this:

```
        public function tomorrow():void {
            var tomorrow:Date =  chooser.selectedDate;
            tomorrow.setDate(tomorrow.getDate() + 1); // fails to update display
            chooser.updateDiaplay();
        }
```

**Comment by pentapache** [comment] 2017-10-25 19:09
This does not work because chooser.selectedDate is being modified and when the model is set with the same value, nothing happens. This is by design. You must create a new Date and not modify the original. Perhaps all components should have an exposed refresh/update method. Not sure how PAYG that is.

**Comment by justinmclean** [comment] 2017-10-25 19:24
Yep as shown in the code snippets above, happing a refresh/update (which I called update display but other names are fine) would simplify users code.

**Comment by Harbs** [comment] 2017-10-29 08:23
I just committed a date utility package to make this kind of thing easier. Your use case would be like this:

        import org.apache.royale.utils.date.*;

        public function tomorrow():void {
            chooser.selectedDate = addDays(chooser.selectedDate);
            date.text = chooser.selectedDate.toDateString();
        }

**Closed by Harbs** 2017-10-29 08:23 UTC

**Comment by Harbs** [comment] 2017-10-29 08:26
FYI, adding arbitrary days/months could easily be done like this:
        import org.apache.royale.utils.date.*;

        public function incrementDays(val:int):void {
            chooser.selectedDate = addDays(chooser.selectedDate,val);
            date.text = chooser.selectedDate.toDateString();
        }
        public function incrementMonth(val:int):void {
            chooser.selectedDate = addMonths(chooser.selectedDate,val);
            date.text = chooser.selectedDate.toDateString();
        }
