### ISSUE TITLE
parentApplication Property not working

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#358] opened 2018-12-27 08:24 UTC
We have downloaded latest apache royale release :https://royale.apache.org/download/
Apache Royale is 0.9.4, released in December, 2018. 
Unable to access parentApplication.CompCode property . Below given example is tested with latest release:
https://github.com/alinakazi/Examples/tree/master/ParentApplication%20property/HelloWorld

**Comment by aharui** [comment] 2018-12-31 07:57
In Flex, does a module's parentApplication return the main Application?  I don't have time to verify that right now, so please verify that is how it worked in Flex.

**Comment by aharui** [comment] 2019-01-01 07:55
I verified that it did work in Flex.  The issue is that ModuleLoader is not setting up the systemManager on the Module.  IMO, UIComponent.addingChild should pass systemManager to the child.  I'm out of time to try that for another 20 hours so feel free to try it yourself.

**Comment by aharui** [comment] 2019-01-02 05:04
fixed in 8c7a8afff3b23004e4a86aebdbff70afd278acb6

**Closed by aharui** 2019-01-02 05:04 UTC
