### ISSUE TITLE
Error: Unexpected exception 'java.lang.NullPointerException'

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#1015] opened 2020-12-18 13:01 UTC
I was compiling my project I got this exception then I again reclone SDK and compile asjs, compiler, and typedefs again and then compile my application but still issue exist, what's the reason for this exception?
Error: Unexpected exception 'java.lang.NullPointerException' at org.apache.royale.compiler.internal.tree.mxml.MXMLTreeBuilder.parseValue:356
![image](https://user-images.githubusercontent.com/42200979/102617588-3f042e00-415b-11eb-8f28-5a56ef1c339f.png)

**Comment by pashminakazi** [comment] 2020-12-18 13:58
In Royale-Compiler **org.apache.royale.compiler.internal.tree.mxml.MXMLTreeBuilder.java**
there is a function named parseValue
In Which there is a line **String typeName = type.getQualifiedName();** which is on line **356**

**Comment by pashminakazi** [comment] 2020-12-21 14:13
@aharui do you have any solution for this problem?

**Comment by joshtynjala** [comment] 2021-01-14 23:16
I tried to reproduce this issue, but I couldn't figure out how. You must have some bad syntax in one of your MXML files, but I can't guess what could be wrong. Your best bet is to start commenting things out until it compiles properly. That should help you narrow it down.

**Comment by joshtynjala** [comment] 2021-01-14 23:30
Closing duplicate of apache/royale-compiler#170

**Closed by joshtynjala** 2021-01-14 23:30 UTC
Labels: bug, help wanted
