### ISSUE TITLE
Datagrid failed after migration from 0.9.7 to 0.9.8 

### ISSUE THREAD

**Issue by Nisaba** [apache/royale-asjs#1178] opened 2022-02-15 17:15 UTC
Hi all,

I developped an application in SDK 0.9.7 derivated from TourDeJewel v.0.9.7

I switched to SDK 0.9.8, but now, all datagrids in my project crash.

Please see attachment.
Any idea ?
Thanks !

![image](https://user-images.githubusercontent.com/34550856/154113957-19850dfc-9e1b-4c6b-8b97-4419178cd28c.png)

**Comment by mjesteve** [comment] 2022-02-15 17:54
Hi,
A lot has changed since version 0.9.7. Version 0.9.10 will be released in the next few days.
The first thing I would recommend is to compile with version 0.9.9 and after that can you isolate an example and share it?

Hiedra

**Comment by mjesteve** [comment] 2022-02-15 18:38
True, 
At https://royale.apache.org/get-involved/ you can access nightly builds "normally" BUT right now the server is down :( 

test https://ci-builds.apache.org/job/Royale/job/Royale-asjs/

**Comment by Nisaba** [comment] 2022-02-15 19:58
OK,
Now, I get the same error with 0.9.9

**Comment by mjesteve** [comment] 2022-02-15 20:51
can you isolate an example and share it?

**Comment by Nisaba** [comment] 2022-02-16 11:45
Here is a sample that crashes my application :

        <j:DataGrid localId="dg1">
            <j:columns>
                <j:DataGridColumn label="Type" dataField="Titre" columnWidth="100"/>
                <j:DataGridColumn label="En cours" dataField="NbEncours" columnWidth="100" align="center"/>
                <j:DataGridColumn label="Annulées" dataField="NbKO" columnWidth="100" align="center"/>
                <j:DataGridColumn label="Terminées" dataField="NbOK" columnWidth="100" align="center"/>
                <j:DataGridColumn label="Total" dataField="NbTotal" columnWidth="100" align="center"/>
            </j:columns>
        </j:DataGrid>

As you can see, it's very simple. It's OK if I comment this datagrid tag

**Comment by mjesteve** [comment] 2022-02-16 12:39
I don't see anything that tells me the origin of the error, are you sure that it is caused by the DataGrid and not, for example, by the "dataProvider" that you surely assign to it?

**Comment by Nisaba** [comment] 2022-02-28 17:07
Hello,
Sorry for the delay.
The dataProvider is OK, all worked well with 0.9.7 framework.

I think the issue is about databinding and the initialisation of the application.
The dataProvider is initialized via a binding variable filled at the startup by a web service.

Are there many changes since 0.9.7 in terms of application initialization and databinding

**Comment by aharui** [comment] 2022-02-28 17:28
If you can provide a simplified test case that can be downloaded and compiled it might help someone find time to debug it.

From: Nisaba ***@***.***>
Reply-To: apache/royale-asjs ***@***.***>
Date: Monday, February 28, 2022 at 9:11 AM
To: apache/royale-asjs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [apache/royale-asjs] Datagrid failed after migration from 0.9.7 to 0.9.8 (Issue #1178)


Hello,
Sorry for the delay.
The dataProvider is OK, all worked well with 0.9.7 framework.

I think the issue is about databinding and the initialisation of the application.
The dataProvider is initialized via a binding variable filled at the startup by a web service.

Are there many changes since 0.9.7 in terms of application initialization and databinding

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapache%2Froyale-asjs%2Fissues%2F1178%23issuecomment-1054471433&data=04%7C01%7Caharui%40adobe.com%7C53180d55c69e4317c4f008d9fadce16e%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637816650711069174%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=WV5SglD1fOmOVDIWCnLNALOk0k1B1obKbWdGbxgjKXk%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAQIK6K2TGKL4LRX5KVXPHTU5OTW3ANCNFSM5OPFNJLQ&data=04%7C01%7Caharui%40adobe.com%7C53180d55c69e4317c4f008d9fadce16e%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637816650711069174%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=%2Bwsr6j2dEgja2l%2FHFy2pGtermzOpWOOKxwc1BDOq10c%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Caharui%40adobe.com%7C53180d55c69e4317c4f008d9fadce16e%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637816650711069174%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=%2FFAvQeU7JirS7QnPVxAtdSqy6zsKFvOie9HKxNJdnkc%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Caharui%40adobe.com%7C53180d55c69e4317c4f008d9fadce16e%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637816650711069174%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=VfoQYPtj54gla4oR716DXWFEtldFW32Xm8r3F1Obm08%3D&reserved=0>.

**Comment by Nisaba** [comment] 2022-02-28 18:49
The application is quite complex, it will take a bit of time to isolate a simplified code, but I will deal with it. 

Anyway, here is what can i say for now :
There is no problem with dataprovider or data binding since even this simple line of code crashes the application : 

<j:DataGrid localId="dg2"/>

The simple fact of putting a datagrid on a page causes the application to crash at startup...

**Comment by joshtynjala** [comment] 2022-02-28 21:52
@Nisaba When you switched from 0.9.7 to a newer version, did you do a clean build? In other words, did you delete your output directory containing the old generated .js files? If not, give that a try.

**Comment by Nisaba** [comment] 2022-03-01 10:41
Great ! it works !
it was as simple as that!!
Thank you for the help !

**Closed** 2022-03-01 15:38 UTC
