### ISSUE TITLE
Compile time issue on accessing a file into script Block

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#529] opened 2019-10-23 12:06 UTC
We have two files 
1. HelloWorld
https://paste.apache.org/1g5n3
2.ControlsExample   (has starting and closing tag TitleWindow)
https://paste.apache.org/ut24j

We want to use ControlsExample in script block of HelloWorld
Unable to compile it. System is unable to access ControlsExample file from HelloWorld

**Comment by aharui** [comment] 2019-10-23 19:39
Please provide the source you are trying to compile.

What do you mean by "use ControlsExample in script block"?  Are you trying to have a component defined in the application's MXML file?  Or use a bunch of XML and assign it to a variable?

**Comment by pashminakazi** [comment] 2019-10-24 06:40
If i am using custom Component in Main File then it works but if i use custom Component in Module it shows an Error on Console :
![image](https://user-images.githubusercontent.com/42200979/67459514-334dd200-f652-11e9-9070-fab2d85a6ab5.png)

Example: 
https://drive.google.com/drive/folders/1Hj35BThQSkJG3m_-1BtLEb8lTCN0YaNG?usp=sharing

**Comment by pashminakazi** [comment] 2019-10-24 07:18
Module can't create a instance for another Module in Script Block
In our Module File we are using
[Bindable] private var frmVehicle:dbzVehicleSetup = new dbzVehicleSetup();
dbzVehicleSetup is a Module.		
![image](https://user-images.githubusercontent.com/42200979/67461717-73638380-f657-11e9-8873-aeeb5b942868.png)

Example:
 https://drive.google.com/file/d/1xidHAdOS5v3v-8FaDfKn1LvZLn6xDDrU/view?usp=sharing

**Comment by aharui** [comment] 2019-10-24 08:43
Please do not use .RAR files.  I am unable to open them.

Please be very careful about the use of the words Component vs Module vs File.

I'm assuming you are using Module and not TitleWindow as mentioned earlier.  If you are using Modules, then you should not reference the module class in some other module's code, or even in the main application's code.  You are supposed to use Interfaces instead.

If you reference the module class, then the compiler will look for a source file or class in a swc and actually link the module's class into the compiled output, which defeats the whole purpose of Modules.  And in order to do that, the Module's source code must either be in the source-path, or the library-path must include a version of the Module's compiled output.

Instead, an Interface should be defined and shared between the module/application that is loading the module and the module itself.

Did your code work in Flex?  If it did, it was probably because the source-path included that module's source file.  But then there would not actually be a need to load the module as it was linked into the loading module or application.

**Closed by aharui** 2019-10-24 08:43 UTC

**Comment by alinakazi** [comment] 2019-10-24 09:43
@aharui 
Please look into this example
https://drive.google.com/drive/folders/1WcrcOdbUfoc6XkOHxSE20j-w-UpqdAJm?usp=sharing

Debug Mode Screenshot
![issue in TitleWindow on another path](https://user-images.githubusercontent.com/36731338/67473580-cb729980-f607-11e9-8100-08c82a527044.png)

when we have TitleWindow and Application/module files on different place error occurs.

**Comment by aharui** [comment] 2019-10-24 17:58
I downloaded the two files, put them in

```
src/HelloWorld.mxml
src/abc/ControlsExample.mxml
```

It compiled and ran.

I don't understand what "different place" means.  Please explain what steps to take to reproduce this problem.

**Comment by alinakazi** [comment] 2019-10-25 06:20
Difference place means one inside abc and one outside abc

Copy this including build file
https://drive.google.com/drive/folders/1WcrcOdbUfoc6XkOHxSE20j-w-UpqdAJm?usp=sharing

And send me your build file.

**Comment by aharui** [comment] 2019-10-25 16:35
I'm not sure what "one inside abc and one outside abc" means.  In the example you linked to, there are only two source files:

```
src\main\royale\HelloWorld.mxml (starting with mx:Application)
src\main\royale\abc\ControlsExample.mxml (starting with mx:TitleWindow)
```

The code in HelloWorld.mxml references `abc.ControlsExample`.

The build script compiles the ControlsExample, but it is not a Application or Module, so I don't understand why it is being compiled.  The compiling overwrites some of the files output during the HelloWorld compile causing HelloWorld to fail.

If you just compile the HelloWorld (compile-shell), it runs just fine as expected.

I'm confused as to what your goal is.  If your goal is to have a Module called abc.ControlsExample, then HelloWorld should not be directly referencing abc.ControlsExample.  If your goal is to use abc.ControlsExample as an MXMLComponent then there is no need to compile ControlsExample.

If the question is how to have an MXML class in a package, then the main tag in ControlsExample should be mx:Application or mx:Module, and when you compile it, you want to specify the `-source-path=src/main/royale` but specify the main file as `src/main/royale/abc/ControlsExample.mxml`.  Then the main module class will be `abc.ControlsExample`.
