### ISSUE TITLE
TypeError: Cannot set property 'oParentForm' of null

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#725] opened 2020-02-19 10:17 UTC
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Accounts Payable from Select in Menu
Go to Sales Commission Scheme from Setups in Menu
File : com/dbz/modules/AR/dbzSalesCommissionScheme.mxml

popUpDetailEntry = new dbzSalesCommissionSchemeDetail();
popUpDetailEntry.oParentForm = this;

oParentForm  is defined in dbzSalesCommissionSchemeDetail
[Bindable] public var oParentForm:Object = null;

On Clicking **Plus (+)** button for detail grid 
function called **fn_AddProduct** and which is setting 

**popUpDetailEntry.oParentForm = this;** and then this exception occurs
![image](https://user-images.githubusercontent.com/42200979/74824660-551e4380-532a-11ea-953a-988338adba25.png)

**Comment by aharui** [comment] 2020-02-21 06:32
I cannot reproduce this on the VDI

**Comment by pashminakazi** [comment] 2020-02-21 06:34
Go to Accounts Payable from Select in Menu
Go to Sales Commission Scheme from Setups in Menu
and click on **+** button

**Comment by pashminakazi** [comment] 2020-02-21 06:35
just a min.I am connecting VDI for 1 min

**Comment by pashminakazi** [comment] 2020-02-21 06:36
Ok,fine now connect VDI

**Comment by pashminakazi** [comment] 2020-02-24 13:00
Check this issue in 
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Accounts Payable from Select in Menu
Go to ATM Rental Payment from Setups in Menu
File : com/dbz/modules/AR/dbzATMRentalPayment.mxml

Open this setup Click on New Button and then Plus button (+)

**Comment by aharui** [comment] 2020-02-24 18:41
An exception was thrown during the loading of the module.

**Comment by aharui** [comment] 2020-02-24 18:45
Special-cased looking for trailing \' in output for MXML.

**Comment by pashminakazi** [comment] 2020-02-25 06:23
So what should i use instead of 
`restrict="0-9,\"`

**Comment by aharui** [comment] 2020-02-25 06:34
This should have been fixed by royale-compiler change ab459138c5f293e2fdafca3c4842182d72d47abd

**Comment by aharui** [comment] 2020-02-25 06:35
Also, a possible workaround would be to use:

`restrict="0-9,\\"`

**Closed** 2020-02-28 18:57 UTC
