### ISSUE TITLE
RegisterClassAlias called before it loaded into index.html

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#1176] opened 2022-01-28 18:23 UTC
I am calling registerClassAlias in my actionscript file  : registerClassAlias("EPS.Model.QueryInfo", QueryInfo);

Example : [RegisterClassAliasExample.zip](https://github.com/apache/royale-asjs/files/7960937/RegisterClassAliasExample.zip)

HelloWorld.mxml : https://paste.apache.org/ux9qa
HelloWorld.as : https://paste.apache.org/njfzi
QueryInfo.as : https://paste.apache.org/p1afp

Output screenshots : 
![image](https://user-images.githubusercontent.com/42200979/151600588-9a873754-0a6b-4b67-9a4e-c0629123c392.png)
![image](https://user-images.githubusercontent.com/42200979/151600603-cffe544f-d633-46f0-b413-d288b3074301.png)
![image](https://user-images.githubusercontent.com/42200979/151600629-5fc672de-c919-4142-8729-539a7dba2f75.png)
![image](https://user-images.githubusercontent.com/42200979/151600684-8696a5f8-3dc0-4c54-96ec-e68769355e91.png)

**Comment by mjesteve** [comment] 2022-01-30 02:40
Hi Pashmina, I think the problem is inside the .as file.
You can't make the call to a function, in this case "registerClassAlias", if it is not inside another method.
Change the content of the .as file for this one:

```
import org.apache.royale.reflection.registerClassAlias;
import com.epsdr.model.QueryInfo;

/** registering class to use. **************************************/

private var queryInfo:QueryInfo;

private function init():void
{
    registerClassAlias("EPS.Model.QueryInfo", QueryInfo);
    example()    
}

private function example():void
{
    var item:QueryInfo = new QueryInfo();
    item.AppealID=1;
    trace(item.AppealID);
}
```
And in the mxml add the call to the init() method:

```
<mx:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                xmlns:mx="library://ns.apache.org/royale/mx"
                xmlns:js="library://ns.apache.org/royale/basic"
				width="600" height="400"
            	initialize="init()">
```
You will see how it works.

**Comment by pashminakazi** [comment] 2022-01-30 13:57
@mjesteve Thank u so much for your help :)

**Comment by mjesteve** [comment] 2022-02-04 09:46
If there is no objection I close the issue. Pashmina?

**Closed** 2022-02-04 23:22 UTC
Labels: help wanted
