### ISSUE TITLE
Uncaught TypeError : Cannot read property 'call' of EventDispatcher.js undefined

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#533] opened 2019-10-29 07:03 UTC
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.

Go to **Retail Inspection** from **Select** in Menu
Go to **Mobile Restriction Setup** from **Setups** in Menu
File : com/dbz/modules/RI/dbzMobileRestrictionSetup

![image](https://user-images.githubusercontent.com/36731338/67744554-17925500-f9df-11e9-9b01-c2ae49f64c44.png)

@aharui Please look into this issue . Thanks in Advance

**Comment by aharui** [comment] 2019-10-29 19:07
I am unable to reproduce this on the VDI.  I keep getting malformed XML errors and then if I ignore those, I got errors that dbzMobileRestriction.css is missing.

**Comment by pashminakazi** [comment] 2019-10-30 09:50
After compiling setups with New SDK on VDI
Every Setup is blank with 
**"Uncaught TypeError : Cannot read property 'call' of EventDispatcher.js undefined"**
Check this issue on VDI 
setups->Companies

**Comment by pashminakazi** [comment] 2019-10-30 09:51
dbzMobileRestrictionSetup is Compiled on VDI

**Comment by aharui** [comment] 2019-10-30 19:03
Seems to be fixed by 4d4a9d0376253f056297d587f38dc2cfa7a10a82

**Closed by aharui** 2019-10-30 19:03 UTC
