### ISSUE TITLE
Uncaught TypeError: Cannot read property 'concat' of null    (DateBase.js:343)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#753] opened 2020-03-11 07:07 UTC
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Accounts Payable from Select in Menu
Go to ATM Rental Income from Setups in Menu
File : com/dbz/modules/AR/dbzATMRentalReceipt.mxml

After providing values in Master and Detail click save button,this Exception will occured 

![image](https://user-images.githubusercontent.com/42200979/76388257-82d73500-638a-11ea-9c6b-c2a9cd5fc863.png)
![image](https://user-images.githubusercontent.com/42200979/76388264-88347f80-638a-11ea-800f-e76b53fd5adb.png)
![image](https://user-images.githubusercontent.com/42200979/76388280-94204180-638a-11ea-968b-c3311d9ffa77.png)

**Comment by aharui** [comment] 2020-03-20 05:23
This is a duplicate of #757

**Closed by aharui** 2020-03-20 05:23 UTC
