### ISSUE TITLE
TypeError: Error #1088: The markup in the document following the root element must be well-formed.

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#524] opened 2019-10-22 09:17 UTC
**Setups-> Foreign Currency -> Rates**
Please check this issue on our VDI.
**Project Details are :**
https://paste.apache.org/cpo8y
File Name : **dbzFCRatesMain**
available in D:\DBIZSOL\Main\Royale\src\com\dbz\modules\Common
![image](https://user-images.githubusercontent.com/42200979/67272672-6a977400-f4d6-11e9-8866-78a2956e9da0.png)

**Comment by aharui** [comment] 2019-10-24 18:11
I was unable to reproduce the "well-formed" error.  There are several exceptions thrown indicating that the application has not been updated.  Any errors reported after a prior exception may be invalid.  When an exception is thrown, it may mean that important code did not run

**Comment by aharui** [comment] 2019-10-24 18:26
I got this error from a different point in the code.  The markup is:


<menuitem id="1" label="File">
		<menuitem id="2" label="System Configuration" module="com/dbz/modules/Common/dbzConsolMainTabs" enabled="true"/>
		<menuitem id="3" label="Exit" module="com/dbz/modules/Common/dbzAppExit" enabled="true"/>
</menuitem>
<menuitem id="1000" label="Select">
		<menuitem id="1005" label="Period" module="com/dbz/modules/Common/dbzSelectParameters" enabled="true"/>
		<menuitem id="1010" type="separator"/> 
		<menuitem id="1015" label="General Ledger" module="com/dbz/modules/GL/dbzGeneralLedgerModule" enabled="true"/>
		<menuitem id="1020" label="Fixed Assets" module="com/dbz/modules/FA/dbzFixedAssetsModule" enabled="true"/>
		<menuitem id="1025" label="Purchase" module="com/dbz/modules/PUR/dbzPurchaseModule" enabled="true"/>
		<menuitem id="1030" label="Accounts Payable" module="com/dbz/modules/AP/dbzAccountsPayableModule" enabled="true"/>
		<menuitem id="1035" label="Inventory" module="com/dbz/modules/INV/dbzInventoryModule" enabled="true"/>
		<menuitem id="1040" label="Accounts Receivable" module="com/dbz/modules/AR/dbzAccountsReceivableModule" enabled="true"/>
		<menuitem id="1055" label="EIS - (Dashboard)" module="com/dbz/modules/EIS/dbzEISModule" enabled="true"/>
		<menuitem id="1060" label="Planning" module="com/dbz/modules/PLAN/dbzPlanModule" enabled="true"/>
		<menuitem id="1065" label="Feasibility" module="com/dbz/modules/FS/dbzFeasibilityModule" enabled="true"/>
		<menuitem id="1068" label="Retail Inspection" module="com/dbz/modules/RI/dbzRetailInspectionModule" enabled="true"/>
</menuitem>
<menuitem id="2000" label="Setups">
		<menuitem id="2005" label="Companies" module="com/dbz/modules/Common/dbzCompanySetup" enabled="true"/>
		<menuitem id="2010" label="Sites" module="com/dbz/modules/Common/dbzSitesSetup" enabled="true"/>
		<menuitem id="2015" label="Cost Centre" module="com/dbz/modules/Common/dbzCostCenterSetup" enabled="true"/>
<menuitem id="2020" label="Foreign Currency">
		<menuitem id="2025" label="Rates" module="com/dbz/modules/Common/dbzFCRatesMain" enabled="true"/>
		<menuitem id="2030" label="Types" module="com/dbz/modules/Common/dbzFCRateType" enabled="true"/>
</menuitem>
		<menuitem id="2035" type="separator"/> 
<menuitem id="2040" label="Documents">
		<menuitem id="2045" label="Configure" module="com/dbz/modules/Common/dbzDocumentTabSetup" enabled="true"/>
		<menuitem id="2050" label="Verification Plans" module="com/dbz/modules/Common/dbzVerificationPlanSetup" enabled="true"/>
		<menuitem id="2055" label="Setup Verification Plans" module="com/dbz/modules/Common/dbzSetUpVerificationPlan" enabled="true"/>
</menuitem>
<menuitem id="2060" label="Product">
		<menuitem id="2065" label="Profile" module="com/dbz/modules/Common/dbzProductProfileSetup" enabled="true"/>
		<menuitem id="2070" label="Measurement Units" module="com/dbz/modules/Common/dbzMeasurementUnitSetup" enabled="true"/>
		<menuitem id="2073" label="Unit Rates" module="com/dbz/modules/Common/dbzUnitRateSetup" enabled="true"/>
		<menuitem id="2075" label="Groups" module="com/dbz/modules/Common/dbzProductGroupSetup" enabled="true"/>
		<menuitem id="2080" label="Conditions" module="com/dbz/modules/Common/dbzProductConditionsSetup" enabled="true"/>
		<menuitem id="2085" label="Analysis 1" module="com/dbz/modules/Common/dbzProductAnalysis1Setup" enabled="true"/>
		<menuitem id="2090" label="Analysis 2" module="com/dbz/modules/Common/dbzProductAnalysis2Setup" enabled="true"/>
		<menuitem id="2095" label="Analysis 3" module="com/dbz/modules/Common/dbzProductAnalysis3Setup" enabled="true"/>
		<menuitem id="2096" label="Analysis 4" module="com/dbz/modules/Common/dbzProductAnalysis4Setup" enabled="true"/>
		<menuitem id="2097" label="Analysis 5" module="com/dbz/modules/Common/dbzProductAnalysis5Setup" enabled="true"/>
		<menuitem id="2098" label="Product Loc Wise S.TaxR" module="com/dbz/modules/Common/dbzProductLocWiseSTaxRMaster" enabled="true"/>
		<menuitem id="2100" label="Product-Wise Store" module="com/dbz/modules/Common/dbzProdWiseStoreSetup" enabled="true"/>
</menuitem>
<menuitem id="2105" label="Store Room">
		<menuitem id="2110" label="Store" module="com/dbz/modules/Common/dbzStoreSetup" enabled="true"/>
		<menuitem id="2115" label="Inventory Types" module="com/dbz/modules/Common/dbzInventoryType" enabled="true"/>
		<menuitem id="2120" label="Distance" module="com/dbz/modules/Common/dbzStoreDistanceSetup" enabled="true"/>
		<menuitem id="2125" label="Freight Zone" module="com/dbz/modules/Common/dbzFreightZoneSetup" enabled="true"/>
		<menuitem id="2130" label="Store City Distance" module="com/dbz/modules/SAL/dbzStoreCityDistanceSetup" enabled="true"/>
</menuitem>
<menuitem id="2150" label="Customer">
		<menuitem id="2155" label="Profile" module="com/dbz/modules/Common/dbzCustomerSetupTabs" enabled="true"/>
		<menuitem id="2160" label="Types" module="com/dbz/modules/SAL/dbzCustomerType" enabled="true"/>
		<menuitem id="2165" label="Category" module="com/dbz/modules/SAL/dbzCustomerCategory" enabled="true"/>
		<menuitem id="2170" label="Segment" module="com/dbz/modules/SAL/dbzCustomerSegment" enabled="true"/>
		<menuitem id="2175" label="Exchange" module="com/dbz/modules/SAL/dbzCustomerExchange" enabled="true"/>
		<menuitem id="2180" label="Vehicle Registration" module="com/dbz/modules/SAL/dbzCustVehicleRegSetup" enabled="true"/>
		<menuitem id="2190" label="Coupon Issuance" module="com/dbz/modules/SAL/dbzCouponIssuanceSetup" enabled="true"/>
</menuitem>
<menuitem id="2220" label="Price">
		<menuitem id="2221" label="Price Entry" module="com/dbz/modules/SAL/dbzPriceEntryTabs" enabled="true"/>
		<menuitem id="2222" label="Title Wise" module="com/dbz/modules/SAL/dbzPriceTitleWiseSetup" enabled="true"/>
		<menuitem id="2223" label="Titles" module="com/dbz/modules/SAL/dbzPriceTitleSetup" enabled="true"/>
		<menuitem id="2224" label="Configuration" module="com/dbz/modules/SAL/dbzPriceTitleConfigSetup" enabled="true"/>
</menuitem>
<menuitem id="2235" label="Carriage/Freight">
		<menuitem id="2240" label="Contractor" module="com/dbz/modules/INV/dbzCarriageContractorSetup" enabled="true"/>
		<menuitem id="2241" label="Freight Forwarders" module="com/dbz/modules/PUR/dbzFreightForwardersSetup" enabled="true"/>
		<menuitem id="2242" label="Vehicle" module="com/dbz/modules/INV/dbzCarriageVehicleSetupTabs" enabled="true"/>
		<menuitem id="2243" label="Route" module="com/dbz/modules/INV/dbzCarriageRouteSetup" enabled="true"/>
		<menuitem id="2244" label="Customer Approved Depot" module="com/dbz/modules/Common/dbzApprovedDepotSetup" enabled="true"/>
		<menuitem id="2245" label="Freight Rate" module="com/dbz/modules/Common/dbzFreightRateSetup" enabled="true"/>
		<menuitem id="2246" label="Driver Setup" module="com/dbz/modules/Common/dbzDriverMasterSetup" enabled="true"/>
		<menuitem id="2248" label="Fill Stations" module="com/dbz/modules/PUR/dbzFillStationSetup" enabled="true"/>
		<menuitem id="2249" label="Tank Lorry Seals Setup" module="com/dbz/modules/SAL/dbzSealsSetup" enabled="true"/>
</menuitem>
		<menuitem id="2236" label="Document Type Category Setup" module="com/dbz/modules/SAL/dbzDocTypeCategorySetup" enabled="true"/>
		<menuitem id="2280" label="Shipment Modes" module="com/dbz/modules/PUR/dbzShipmentModeSetup" enabled="true"/>
		<menuitem id="2285" label="Transportation Type" module="com/dbz/modules/PUR/dbzTransportationModeSetup" enabled="true"/>
		<menuitem id="2290" label="Terms and Conditions" module="com/dbz/modules/Common/dbzTermsandConditions" enabled="true"/>
		<menuitem id="2295" label="Delivery Terms" module="com/dbz/modules/PUR/dbzDeliveryTermsSetup" enabled="true"/>
		<menuitem id="2315" label="Salesman " module="com/dbz/modules/SAL/dbzSalesmanSetup" enabled="true"/>
		<menuitem id="2320" label="Brand" module="com/dbz/modules/SAL/dbzBrandSetup" enabled="true"/>
		<menuitem id="2325" label="Packing" module="com/dbz/modules/SAL/dbzPackingSetup" enabled="true"/>
		<menuitem id="2326" label="Temperature Compensation " module="com/dbz/modules/SAL/dbzTemperatureCompenSetup" enabled="true"/>
		<menuitem id="2335" label="Shifts" module="com/dbz/modules/Common/dbzShiftSetup" enabled="true"/>
<menuitem id="2475" label="Misc.">
		<menuitem id="2480" label="Cities" module="com/dbz/modules/Common/dbzCitySetup" enabled="true"/>
		<menuitem id="2485" label="Employees" module="com/dbz/modules/Common/dbzEmployeeSetup" enabled="true"/>
		<menuitem id="2490" label="Departments" module="com/dbz/modules/Common/dbzDepartmentSetup" enabled="true"/>
		<menuitem id="2491" label="Designations" module="com/dbz/modules/Common/dbzDesignationSetup" enabled="true"/>
		<menuitem id="2492" label="Oracle Integration" module="com/dbz/modules/Common/dbzOraIntConfigSetup" enabled="true"/>
		<menuitem id="2493" label="CV Setup" module="com/dbz/modules/Common/dbzCVSetup" enabled="true"/>
		<menuitem id="2660" label="Continent" module="com/dbz/modules/Common/dbzContinentSetup" enabled="true"/>
		<menuitem id="2665" label="Country" module="com/dbz/modules/Common/dbzCountrySetup" enabled="true"/>
		<menuitem id="2670" label="Province" module="com/dbz/modules/Common/dbzProvinceSetup" enabled="true"/>
</menuitem>
		<menuitem id="3805" label="Location Setup" module="com/dbz/modules/RI/dbzLocationSetup" enabled="true"/>
		<menuitem id="4000" type="separator"/> 
<menuitem id="4005" label="Security">
		<menuitem id="4010" label="Users" module="com/dbz/modules/SEC/dbzUsersTabSetup" enabled="true"/>
		<menuitem id="4015" label="Groups" module="com/dbz/modules/SEC/dbzSecurityPolicy" enabled="true"/>
		<menuitem id="4020" label="Group Privileges" module="com/dbz/modules/Common/dbzGroupPrivileges" enabled="true"/>
		<menuitem id="4025" label="User Sites" module="com/dbz/modules/Common/dbzUserSitesSetup" enabled="true"/>
</menuitem>
		<menuitem id="4030" label="Preferences" module="com/dbz/modules/Common/dbzPreferences" enabled="true"/>
</menuitem>
<menuitem id="3300" label="Sales">
		<menuitem id="3305" label="Customer Inquiry-CI" module="com/dbz/modules/SAL/dbzCustomerEnquiryTabs" enabled="true"/>
		<menuitem id="3310" label="Delivery Schedule" module="com/dbz/modules/SAL/dbzDeliveryScheduleTabs" enabled="true"/>
		<menuitem id="3315" label="Sales Quotation-SQ" module="com/dbz/modules/SAL/dbzSalesQuotationTabs" enabled="true"/>
		<menuitem id="3320" label="Sales Contract-SC" module="com/dbz/modules/SAL/dbzSalesContractTabs" enabled="true"/>
		<menuitem id="3325" label="Sales Order-SO" module="com/dbz/modules/SAL/dbzSalesOrderTabs" enabled="true"/>
		<menuitem id="3330" label="Delivery Order - DO" module="com/dbz/modules/SAL/dbzDeliveryOrderTabs" enabled="true"/>
		<menuitem id="3335" label="Logistic Indent Note-LIN" module="com/dbz/modules/SAL/dbzLogisticIndentSheetTabs" enabled="true"/>
		<menuitem id="3340" label="ProductUpliftAuthorization-PUA" module="com/dbz/modules/SAL/dbzDeliveryChallanTabs" enabled="true"/>
		<menuitem id="3345" label="Cylinder Receipt" module="com/dbz/modules/SAL/dbzDeliveryConfirmationTabs" enabled="true"/>
		<menuitem id="3350" label="Loading Note-LDN" module="com/dbz/modules/SAL/dbzLoadingNoteTabs" enabled="true"/>
		<menuitem id="3360" label="Gate Pass-IN" module="com/dbz/modules/SAL/dbzGatePassOutTabs" enabled="true"/>
		<menuitem id="3365" label="Gate Pass-OUT" module="com/dbz/modules/SAL/dbzGatePassInTabs" enabled="true"/>
		<menuitem id="3370" label="Sales Return-SR" module="com/dbz/modules/SAL/dbzSalesReturnTabs" enabled="true"/>
		<menuitem id="3375" type="separator"/> 
		<menuitem id="3380" label="Repair Jobs Entry" module="com/dbz/modules/SAL/dbzRepairJobEntry" enabled="true"/>
		<menuitem id="3390" label="Contract for Lubricant" module="com/dbz/modules/SAL/dbzContractLubricant" enabled="true"/>
		<menuitem id="3395" label="Lubricant Freight" module="com/dbz/modules/SAL/dbzLubricantFreight" enabled="true"/>
</menuitem>
<menuitem id="7000" label="Process">
		<menuitem id="7001" label="Date Closing/Opening" module="com/dbz/modules/Process/dbzClosedDates" enabled="true"/>
<menuitem id="7002" label="Period End">
		<menuitem id="7003" label="Temporary" module="com/dbz/modules/Process/dbzTemporaryPeriodEndTabs" enabled="true"/>
		<menuitem id="7004" label="Permanent" module="com/dbz/modules/Process/dbzParmanentPeriodEndTabs" enabled="true"/>
		<menuitem id="7005" type="separator"/> 
		<menuitem id="7006" label="Cancel Temporary Period End" module="com/dbz/modules/Process/dbzCancelTemporaryPeriodTabs" enabled="true"/>
</menuitem>
<menuitem id="7007" label="Year End">
		<menuitem id="7008" label="Temporary" module="com/dbz/modules/Process/dbzTemporaryYearEndTabs" enabled="true"/>
		<menuitem id="7009" label="Permanent" module="com/dbz/modules/Process/dbzPermanentYearEndTabs" enabled="true"/>
</menuitem>
		<menuitem id="7026" type="separator"/> 
		<menuitem id="7027" label="Define A/c for Voucher" module="com/dbz/modules/Process/dbzDefineAccVoucher" enabled="true"/>
		<menuitem id="7028" label="Generate Voucher(s)" module="com/dbz/modules/Process/dbzCreateVoucher" enabled="true"/>
		<menuitem id="7029" label="Generate Gain/Loss Voucher" module="com/dbz/modules/Process/dbzPLVoucher" enabled="true"/>
		<menuitem id="7030" label="Oracle Integration" module="com/dbz/modules/Process/dbzOracleIntegration" enabled="true"/>
		<menuitem id="7031" type="separator"/> 
		<menuitem id="7032" label="Re-calculate Sale Price" module="com/dbz/modules/Process/dbzRecalculateSalePrice" enabled="true"/>
		<menuitem id="7033" label="Bulk Invoice Generation" module="com/dbz/modules/Process/dbzBulkInvoiceGeneration" enabled="true"/>
		<menuitem id="7034" label="Incentive Plan" module="com/dbz/modules/SAL/dbzIncentivePlanTabs" enabled="true"/>
		<menuitem id="7035" type="separator"/> 
		<menuitem id="7043" label="Verify Documents" module="com/dbz/modules/Process/dbzVerifyPostDocuments" enabled="true"/>
		<menuitem id="7043" label="Re-calculate Primary Freight" module="com/dbz/modules/Process/dbzRecalculatePrimaryFreight" enabled="true"/>
</menuitem>
<menuitem id="8000" label="Enquiries">
		<menuitem id="8005" label="Activity Log" module="com/dbz/reports/view/Common/dbzActivityLog" enabled="true"/>
		<menuitem id="8010" label="Track Log" module="com/dbz/reports/view/Common/dbzTrackLog" enabled="true"/>
		<menuitem id="8015" type="separator"/> 
		<menuitem id="8020" label="Configure Reports" module="com/dbz/modules/Common/dbzConfigureEnquiries" enabled="true"/>
		<menuitem id="8025" label="View Reports" module="com/dbz/modules/Common/dbzViewEnquiries" enabled="true"/>
		<menuitem id="8030" type="separator"/> 
		<menuitem id="8035" label="User Privileges" module="com/dbz/reports/view/SEC/dbzGroupPrivileges" enabled="true"/>
		<menuitem id="8040" label="Group Permissions" module="com/dbz/reports/view/SEC/dbzGroupPermissionReport" enabled="true"/>
		<menuitem id="8045" label="Online Users" module="com/dbz/modules/Common/dbzLoggedUser" enabled="true"/>
		<menuitem id="8050" type="separator"/> 
		<menuitem id="8070" label="Notification" module="com/dbz/modules/Process/dbzDocsNotification" enabled="true"/>
</menuitem>
<menuitem id="9000" label="Reports">
		<menuitem id="9125" label="Period Status Report" module="com/dbz/reports/view/Common/dbzPeriodStatusReport" enabled="true"/>
		<menuitem id="9130" label="Year Status Report" module="com/dbz/reports/view/Common/dbzYearStatusReport" enabled="true"/>
		<menuitem id="9500" label="Product Ledger" module="com/dbz/reports/view/INV/dbzProductLedgerTab" enabled="true"/>
		<menuitem id="9505" label="Sales Ledger" module="com/dbz/reports/view/SAL/dbzSalesLedger" enabled="true"/>
		<menuitem id="9510" label="Sales Summary" module="com/dbz/reports/view/SAL/dbzSalesSummary" enabled="true"/>
		<menuitem id="9512" label="Sales Summary-New" module="com/dbz/reports/view/SAL/dbzSalesSummary2" enabled="true"/>
		<menuitem id="9515" label="Sales Summary-Segment Wise" module="com/dbz/reports/view/SAL/dbzSalesSummarySegmentWise" enabled="true"/>
		<menuitem id="9517" type="separator"/> 
		<menuitem id="9520" label="Customer Ledger" module="com/dbz/reports/view/SAL/dbzCustomerLedger" enabled="true"/>
		<menuitem id="9525" label="Customer Balances" module="com/dbz/reports/view/SAL/dbzCustomerBalances" enabled="true"/>
		<menuitem id="9535" type="separator"/> 
		<menuitem id="9540" label="Sales Tax Return" module="com/dbz/reports/view/SAL/dbzSalesTaxReturn" enabled="true"/>
		<menuitem id="9545" label="Sales Tax Register" module="com/dbz/reports/view/SAL/dbzSalesTaxRegister" enabled="true"/>
		<menuitem id="9551" label="Sales Certificate" module="com/dbz/reports/view/SAL/dbzSalesTaxCertificate" enabled="true"/>
		<menuitem id="9552" label="Tax Payment Chalan" module="com/dbz/reports/view/SAL/dbzTaxPaymentChalan" enabled="true"/>
		<menuitem id="9553" label="Income Tax Withholding Certificate" module="com/dbz/reports/view/SAL/dbzTaxCertificate42" enabled="true"/>
		<menuitem id="9555" type="separator"/> 
		<menuitem id="9560" label="Sales Detail Report" module="com/dbz/reports/view/SAL/dbzSalesDetailReport" enabled="true"/>
		<menuitem id="9565" label="Sales Invoice-SI Report Date wise" module="com/dbz/reports/view/SAL/dbzSalesInvoiceReportDateWise" enabled="true"/>
		<menuitem id="9570" label="Daily Delivery Order - DO" module="com/dbz/reports/view/SAL/dbzDailyDeliveryOrders" enabled="true"/>
		<menuitem id="9585" label="Monthly Delivered Weight Variance" module="com/dbz/reports/view/SAL/dbzDeliveryMonthlyWeightVariance" enabled="true"/>
		<menuitem id="9590" label="Bill Wise Aging" module="com/dbz/reports/view/PUR/dbzBillWiseAging" enabled="true"/>
		<menuitem id="9591" type="separator"/> 
<menuitem id="9595" label="Lists">
		<menuitem id="9600" label="List of Sales Quotation-SQ" module="com/dbz/reports/view/SAL/dbzListOfSalesQuotation" enabled="true"/>
		<menuitem id="9605" label="List of Sales Order-SO" module="com/dbz/reports/view/SAL/dbzListOfSalesOrders" enabled="true"/>
		<menuitem id="9610" label="List of Pending Sales Order-SO" module="com/dbz/reports/view/SAL/dbzListOfPendingSalesOrders" enabled="true"/>
		<menuitem id="9615" label="List of Delivery Order - DO" module="com/dbz/reports/view/SAL/dbzListOfDeliveryOrders" enabled="true"/>
		<menuitem id="9620" label="List of ProductUpliftAuthorization-PUA" module="com/dbz/reports/view/SAL/dbzListOfDeliveryChallans" enabled="true"/>
		<menuitem id="9625" label="List of Pending Sales Invoice-SI" module="com/dbz/reports/view/SAL/dbzListOfPendingSalesInvoices" enabled="true"/>
		<menuitem id="9635" label="List of Sales Return-SR" module="com/dbz/reports/view/SAL/dbzListOfSalesReturn" enabled="true"/>
		<menuitem id="9640" label="List of Mismatched Sales Invoice-SI & Bank Receipt" module="com/dbz/reports/view/SAL/dbzListOfMismatchedInvoicesAndReceipts" enabled="true"/>
</menuitem>
<menuitem id="9645" label="Misc">
		<menuitem id="9675" label="Freight Revision" module="com/dbz/reports/view/SAL/dbzFreightVariation" enabled="true"/>
		<menuitem id="9685" label="List Of Outstanding Cylinders As On" module="com/dbz/reports/view/SAL/dbzListOfOutstandingCylindersAsOn" enabled="true"/>
		<menuitem id="9690" label="Carr Contractor Bill Reconcilation" module="com/dbz/reports/view/SAL/dbzCarrConBillReconcilation" enabled="true"/>
		<menuitem id="9695" label="Freight Calculation " module="com/dbz/reports/view/SAL/dbzFreightCalCar" enabled="true"/>
		<menuitem id="9700" label="Primary Freight Calculation " module="com/dbz/reports/view/SAL/dbzPrimaryFreightCal" enabled="true"/>
		<menuitem id="9705" label="Month to date Purchases and Dispatch Summary " module="com/dbz/reports/view/PUR/dbzMonthtodatepurchasesanddispatchsummary" enabled="true"/>
		<menuitem id="9710" label="OGRA Reports - POLGAS" module="com/dbz/reports/view/SAL/dbzOGRAReports" enabled="true"/>
		<menuitem id="9715" label="OGRA Reports - CAPGAS" module="com/dbz/reports/view/SAL/dbzOGRAReportsCAPGas" enabled="true"/>
		<menuitem id="9720" label="Cylinders Purchase/Delivery" module="com/dbz/reports/view/SAL/dbzCylinderPurchase" enabled="true"/>
		<menuitem id="9725" label="Customer Vehicle-Wise Credit Bill" module="com/dbz/reports/view/SAL/dbzCouponIssuance" enabled="true"/>
</menuitem>
		<menuitem id="9948" type="separator"/> 
</menuitem>
<menuitem id="17000" label="Help">
</menuitem>

**Comment by aharui** [comment] 2019-10-24 18:39
An XML validator said that:

`		<menuitem id="9640" label="List of Mismatched Sales Invoice-SI & Bank Receipt" module="com/dbz/reports/view/SAL/dbzListOfMismatchedInvoicesAndReceipts" enabled="true"/>
`

is not valid because of the '&' in "SI & Bank Receipt".  It should be ""SI &amp; Bank Receipt".  You will need to have the service return valid XML or find and fix these in the string before passing in to XMLList.

If you get this error in other places, click on the XMLList constructor in the debugger's Call Stack, and display the string that was passed in, and check it in an XML validator.

**Closed by aharui** 2019-10-24 18:39 UTC
