### ISSUE TITLE
Issue in dbzAttachmentPopup 

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#506] opened 2019-10-16 10:41 UTC
File is compiled successfully but has run time issues
file:
https://paste.apache.org/e62kx

Test case is available on VDI.

**Comment by alinakazi** [comment] 2019-10-16 11:51
Project Details are :
https://paste.apache.org/cpo8y

**Comment by pashminakazi** [comment] 2019-10-16 11:58
Setups->Product->Profile (dbzProductProfileSetup)
![image](https://user-images.githubusercontent.com/42200979/66916866-9d082380-f035-11e9-92cb-3514b01e5b30.png)


Setups-> Item Inspection Reason (dbzReasonTypeSetup)
![image](https://user-images.githubusercontent.com/42200979/66916976-db9dde00-f035-11e9-8bd4-e80c353b1609.png)

**Comment by aharui** [comment] 2019-10-19 07:07
Duplicate of #514

**Comment by aharui** [comment] 2019-10-21 00:52
I am no longer seeing the 'nullthis' error (Setups -> Products -> Profile)

**Comment by aharui** [comment] 2019-10-21 18:54
I am no longer seeing the other error (Setups -> Item Inspection Reason)

**Closed by aharui** 2019-10-21 18:54 UTC

**Comment by alinakazi** [comment] 2019-10-21 19:27
Item inspection reason is opened on vdi.
Yes now it is ok no error on debugger console.

Thanks alot Alex.

Regards,
Aleena
