### ISSUE TITLE
AdvancedDataGrid doesn't fetch Java side Data 

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#397] opened 2019-02-21 11:20 UTC
I have Created 2 AdvancedDataGrid one with Java Side Data and Second with Manual Data
With ManualData AdvancedDataGrid works Properly But with RemoteObject it doesn't Populate the grid
I tried a lot to make it work but it doesn't work.

In flex, we were using 
gridDataProvider = e.result as ArrayCollection
and it populates the grid 

In apache, i tried e.result as ArrayCollection and many more attempts like 
myGrid= e.result as Array
gridDataProvider = new ArrayCollection(gridarray);
when I trace them it was undefined..

Now I use 
                                var myGrid:Array = new Array(e.result);
				trace(myGrid);
				var gridDataProvider:ArrayCollection = new ArrayCollection([myGrid]);
				trace(gridDataProvider);
And Data of Java Side Method is shown now in trace: 
![advanceddatagrid](https://user-images.githubusercontent.com/42200979/53165108-aef30d00-35f3-11e9-8258-98cae66692e3.png)

Manual Data is shown in AdvancedDataGrid but java side AdvancedDataGrid is empty 
Screenshot: 
![output](https://user-images.githubusercontent.com/42200979/53165186-e06bd880-35f3-11e9-8d4e-4a88e04ae36a.png)

HelloWorld.mxml: https://paste.apache.org/mP0s
I am also pasting below my serverside code for your reference
shmCompanySetupBO.java: https://paste.apache.org/YLeg

**Comment by aharui** [comment] 2019-02-22 06:11
If you debug the Flex (not Royale) version, what is returned from the server?  Is it an Array or ArrayCollection and was are the elements of the Array or ArrayCollection?  Are they plain Objects, ObjectProxy or some Value Object?

Then debug the Royale version.  If you are not getting the same data, then don't even worry about AdvancedDataGrid, first figure out why you are not getting the right data.

**Comment by pashminakazi** [comment] 2019-02-22 08:47
In Flex,Data returned from server is List and we assign data to ArrayCollection.
In Royale,Data returned from server is List and we assign data to Array and then  Array to ArrayCollection then it shows the Data in Trace..
Can you tell me In Royale,how to retrieve list type data into ArrayCollection if i was doing wrong pattern to get data...

**Comment by pashminakazi** [comment] 2019-02-22 08:50
Returned From Java In Flex and Royale
![image](https://user-images.githubusercontent.com/42200979/53230516-ab6d8d80-36a8-11e9-94ee-cfa187bbec8a.png)

**Comment by greg-dove** [comment] 2019-02-22 09:14
Hi, this might be related to one of the warnings I had when I pushed the
updated AMFBinaryData not so long ago.

clientside amf support is not yet ready for general use because it has some
custom hardcoded support for receiving ArrayCollection as ArrayList. I plan
to update it in the coming days which should solve the problem with
receiving ArrayCollection instead of ArrayList, or it could allow you to
remap whatever alias the server is sending to ArrayCollection if that is
also IExernalizable and compatible.
At the moment the client code has custom code that sends both mx
ArrayCollection and royale ArrayList as mx ArrayCollection to the server,
and receives mx ArrayCollection as royale ArrayList. This was a useful
approach when porting legacy code from flex, but is not something that
would be needed long term I think.

With IExternalizable support it will be fixed in the coming days for more
general use.

-Greg

**Comment by aharui** [comment] 2019-02-25 09:39
@greg-dove Does Carlos's app use ArrayCollection?  What is the ETA for proving that ArrayCollection works or not?

**Comment by aharui** [comment] 2019-02-25 09:42
@pashminakazi "List" is a UI widget like mx.controls.List or spark.components.List and would not be added to an ArrayCollection.  Are you referring to some other class?  If so, what is the full package name of the class?

The screenshot seems to be showing the Java side.  What we need to know is what is received in Flash in the client in Flex and in Royale.

**Comment by carlosrovira** [comment] 2019-02-25 15:33
Hi Alex,

we don't use ArrayCollection. Only ArrayList, since Jewel was created with ArrayList, and the change to AC was not easy at that time.

**Comment by greg-dove** [comment] 2019-02-25 18:03
Hi Alex,

'Does Carlos's app use ArrayCollection? What is the ETA for proving that
ArrayCollection works or not?  '

Carlos already replied for the first question (answer is no, but we were
migrating some code, so I had it sending ArrayCollection *and* ArrayList as
ArrayCollection alias for transition, always receiving ArrayCollection as
ArrayList). I warned about this before adding the code as-is.

ETA:
I am currently working on it. I expect to come back to AMFBinaryData later
today, after finishing some related changes in reflection. I have been
focused more on reflection improvements to support 'dynamic' which I will
be adding at the same time as IExternalizable support (ArrayCollection).
There's a separate thread about all this. I will be pushing to a branch so
Harbs can check the implications of a small change I had to make in
BinaryData to match the flash interfaces on AMFBinaryData (which will now
extend BinaryData).

So maybe tomorrow it will be available. I think the work to finish this up
for AMFBinaryData will not be difficult once the reflection support is
working for dynamic. It is almost done, with some limitations (it requires
js-default-initializers to be on otherwise it won't be reliable in more
general use).
For final AMFBinaryData changes, it depends how long it will take to create
a whole lot of unit tests for that, but regardless, I can push it as WIP
while I am still working on that, because it will be in a branch.
I think ETA is realistically by end of tomorrow local ( new
Date(1551247200000) ), although I hope it might be earlier.

**Comment by greg-dove** [comment] 2019-02-27 05:00
Just a quick ETA update. The reflection changes took longer than expected, but I am currently working through the AMFBinaryData updates.  I may need one more day for this, I think. If I can, I will push the reflection changes to an **amf_updates** branch tonight. This has the Unit_Tests manual test working again, which is now what I am using to work through things and match results between swf and js. It might be easier to push everything tomorrow.... I will see.

**Comment by pashminakazi** [comment] 2019-02-27 06:22
@aharui 
In Flex if we do arcCompData = e.result as ArrayCollection 
Received in Flash in the client in Flex: 
![flexdebug](https://user-images.githubusercontent.com/42200979/53469990-e2191e80-3a81-11e9-9f01-867e2f6ee4f7.png)

In Royale if we do arcCompData = e.result as ArrayCollection 
then arcCompData is undefined

**Comment by aharui** [comment] 2019-02-27 06:25
OK, so that indicates that an ArrayCollection is being sent via AMF.  If you can wait for Greg's changes that would be best.

**Comment by greg-dove** [comment] 2019-02-27 06:27
if you are seeing e.result as an ArrayList, then yes, this is known. I hope to have this addressed within 24 hours (in a branch)

**Comment by pashminakazi** [comment] 2019-02-27 06:55
@aharui @greg-dove  @carlosrovira 
Thanks

**Comment by greg-dove** [comment] 2019-02-28 08:13
@pashminakazi I have continued to work on this today, and have made a lot of progress, I am verifying everything against flash player. I'm sorry but I need one more day. I have Exernalizable unit tests passing which means I can start to test ArrayCollection and others in the remoting tomorrow. So I do have solid reason to believe I will get this in after another day

**Comment by pashminakazi** [comment] 2019-02-28 08:40
@greg-dove
Ok Thanks
No Problem.
No need to say Sorry

**Comment by greg-dove** [comment] 2019-03-01 07:36
@pashminakazi I did not try advanced use of small messaging yet. But hopefully you will see better results now for ArrayCollection using the amf_updates branch. Please let me know if you see problems, and open a new issue and assign to me, preferably with a simple example to reproduce any issue you see.

**Comment by pashminakazi** [comment] 2019-03-04 07:27
@greg-dove Thanks for your help
I have Created another issue regarding AdvancedDataGrid and assigned it to you
Issue#398

**Closed** 2019-03-06 07:38 UTC
Labels: help wanted
