### ISSUE TITLE
Date should be selected by Default

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#688] opened 2020-01-20 07:49 UTC
After pressing new button Datefield should not be "/ / /" there should be default selection of date
![Date default selection](https://user-images.githubusercontent.com/42200979/72707878-4dc91600-3b83-11ea-84bd-d5f7ee88ed11.gif)

**Comment by aharui** [comment] 2020-01-20 08:30
Please, no more videos!  Please instead describe the inputs and actual vs expected outputs.  In this case, is this a regular DateField or your subclass?  What value is being assigned to the DateField?  If this is your MaskedDateField subclass, do you have the same problem assigning the same value to a regular DateField in a simple test case?

If so, attach the test case.  If not, you will have to debug the logic in your subclass.

**Comment by pashminakazi** [comment] 2020-01-20 10:02
DateField Example :
https://paste.apache.org/a0wcj
there's no default selection in mx:DateField 
and if i open 1st datefield and then 2nd datefield,
1st datefield should be closed

**Comment by aharui** [comment] 2020-01-20 18:29
The example should work properly with changes
2dc9ae1d3519a711a72627c4896694eaca58936d
c67a59e88cfd5f197a6daaa05956a365e4a0346d

**Comment by pashminakazi** [comment] 2020-01-21 06:01
Still no default selection of date,when i press NEW button all fields will be reset and datefield is like 
"/ / /" instead of date

**Comment by aharui** [comment] 2020-01-21 06:06
What code sets the datefield to today's date?  What value is it using?  If you use the same code in the test case does it work?  If so, then the problem is in your MaskedDateField code and you'll have to debug how that code works.

**Comment by pashminakazi** [comment] 2020-01-21 06:09
there's no code which is setting datefield to today's date.
In Flex when we reset datefield it is automatically setted to today's date.

**Comment by pashminakazi** [comment] 2020-01-21 06:10
In simple test case of DateField,there is no default selection.

**Comment by aharui** [comment] 2020-01-21 06:13
How do you reset it?  Do you create a new one?  Set some values on an existing one?

**Comment by pashminakazi** [comment] 2020-01-21 06:15
Just make this example working
https://paste.apache.org/a0wcj
When i open index.html datefield is blank.there should be today's date in datefield
![image](https://user-images.githubusercontent.com/42200979/72779963-436c5200-3c3f-11ea-90b7-84238acfa406.png)

**Comment by aharui** [comment] 2020-01-21 06:19
Did you verify that this example populates the DateField in Flex?  I might be mis-remembering, but I thought that DateField does not populate the TextInput in Flex so Royale doesn't either.  I think your custom DateField populates the TextInput and that your code is not working correctly.  It might still be a Royale component issue, but we should not change the default functionality if we don't have to.  If Flex does not populate the TextInput, neither should Flex.

**Comment by aharui** [comment] 2020-01-23 23:43
Should be fixed by 462df29dbf897891acdac1a52eaebd23ddb952ff

**Closed by aharui** 2020-01-23 23:43 UTC
