### ISSUE TITLE
Auto-Generated Code is Duplicate

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#602] opened 2019-12-02 10:33 UTC
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Fixed Assets from Select in Menu
Go to Authorized Person from Setups in Menu
File : com/dbz/modules/FA/dbzAuthorizedPerson.mxml

Code field is MaskedTextField and it is auto-generated field
On New Record --> Auto-generated field should have dashes (----),So the user can understand that it is Auto-generated field.
![MaskedTextInput AutoGenerated](https://user-images.githubusercontent.com/42200979/69952063-3e7d0300-1518-11ea-9169-06871dba0aeb.gif)

In this Setup there is already two field with Code 0001 and 0002.
when I save new record with description,Code is auto-generated.New Record Saved with code 0000.
Now when I want to Save fourth Record the Auto-generated code should be 0004.
But it is not generating correct code and the message appears 
"You have specified duplicate value. Please change Duplicate Value"

![image](https://user-images.githubusercontent.com/42200979/69952360-d5e25600-1518-11ea-9013-814b166fc87c.png)

dbzAuthorizedPerson is using lib File dbzSetupList.mxml
these all checks are in dbzSetupList.mxml like
 if (this.com_dbz_modules_components_dbzSetupList_strServerMessage.indexOf("ORA-00001: unique constraint") >= 0)
mx.controls.Alert.show("You have specified duplicate value.\nPlease change Duplicate Value.");

**Comment by aharui** [comment] 2019-12-03 03:36
I cannot get FixedAssets to load and change the menu.  I even edited dbzFixedAssetsModule and added a second parentMxmlDocument to avoid that exception but the server is returning a null pointer exception.

Please make sure these modules are more functional.  Also the code page in the command prompt window is set to something strange so backslash and quote are not working.

**Comment by pashminakazi** [comment] 2019-12-03 07:01
@aharui Check now on VDI

**Comment by aharui** [comment] 2019-12-04 01:41
I think the code that generates a unique code is supposed to be dbzUtil.as balanceCode, but for me it does not do anything and results in "", not 0000.  I will need more explicit steps as to how to get a unique code.

**Comment by pashminakazi** [comment] 2019-12-04 06:12
@aharui Ok thanks,Please find a solution for this So we can send Our setups to QA team.

**Comment by aharui** [comment] 2019-12-04 07:01
Please verify that you can reproduce this problem on the VDI.  Please also verify that balanceCode is the source that generates a new code and explain which code paths it should take.  I keep getting an Alert saying that no code is specified.

I am not currently using the VDI and will be working on other things for about an hour.

**Comment by pashminakazi** [comment] 2019-12-04 13:24
shmutil.as in Flex File : https://paste.apache.org/cjksv
dbzutil.as in Royale File : https://paste.apache.org/zs855

I have debug the source. but i didn't find any change that makes it different than flex.
also , balanceCode method has no change.

**Comment by aharui** [comment] 2019-12-04 19:14
When you debugged it, did balanceCode generate a unique code?  If so, what code paths in balanceCode did it use?  It doesn't matter whether the source has changed or not, what matters is how it runs.

For example, it is mentioned above that on a new record, the code field should be set to dashes, but I do not see that happening in the attached image/video or when I run it.  I would think that would be important to how balanceCode works.

Either you have to explain to me how your code should work, or debug through your code yourself and identify that it is working correctly.  I can go figure it out, but it is inefficient for me to do so.  I am mostly here to help with SDK issues where SDK code was supposed to take some input and return some output but doesn't.

**Comment by aharui** [comment] 2019-12-05 00:53
I spend a few more minutes investigating.  I noticed that when using Feasibility/SubCategoryType that a new entry had an empty code field but still generated a unique code, but when I tried a new entry in this AuthorizedPerson setup, I got an Alert saying that a code needed to be specified.

It looks like there is a check in dbzSetupList fn_validateRecord() that permits certain ST_DOC_IDs to proceed past this Alert, but AuthorizedPersons DOC_ID is not one of them.  This makes me think that the VDI does not have the same dbzSetupList as the one you are using.

**Comment by pashminakazi** [comment] 2019-12-05 08:08
I have checked in Flex ,Authorized Person is taking input for Code field.
In MaskedTextInput if I replace super.text = _working.join(""); with super.text; then i will take input but on saving record It says "You have not specified Code"

In Flex :
![Code field in Flex](https://user-images.githubusercontent.com/42200979/70215876-429b6180-1760-11ea-8a2f-deecf492016c.gif)


In Royale :
![Code field in Royale](https://user-images.githubusercontent.com/42200979/70215884-45965200-1760-11ea-957e-4589141c523c.gif)

Please Check on VDI

**Comment by aharui** [comment] 2019-12-05 08:12
In theory, you can run the Flex debugger and the browser debugger at the same time and set the same breakpoints and step through the code until something different happens.

The code I saw seems to pass the Code text to a service call to get the actual code to use.  It could be that the Royale version is not passing the right thing to the service call or not handling the result correctly.

**Comment by pashminakazi** [comment] 2019-12-05 08:20
In flex we cannot inspect and debug..there are some restrictions on our Flex Code.

If I replace super.text = _working.join(""); with super.text;  In MaskedTextInput then i will take input but on saving record It says "You have not specified Code"

Then I added authorizedPerson ST_DOC_ID In dbzSetupList which is "237" 
if (this.CodeObject.text == "" && this.ST_DOC_ID != "582" **&& this.ST_DOC_ID != "237"** && this.ST_DOC_ID != "587" && this.ST_DOC_ID != "589" && this.ST_DOC_ID != "584" && this.ST_DOC_ID != "586" && this.ST_DOC_ID != "592" && this.ST_DOC_ID != "583" && this.ST_DOC_ID != "581" && this.ST_DOC_ID != "588" && this.ST_DOC_ID != "590" && this.ST_DOC_ID != "580" && this.ST_DOC_ID != "585" && this.ST_DOC_ID != "591" && this.ST_DOC_ID != "751" && this.ST_DOC_ID != "652" && this.ST_DOC_ID != "654" && this.ST_DOC_ID != "660" && this.ST_DOC_ID != "661" && this.HostFrm.ST_DOC_ID != '623' && this.HostFrm.ST_DOC_ID != '629' && this.HostFrm.ST_DOC_ID != '688' && this.HostFrm.ST_DOC_ID != '689') {
    mx.controls.Alert.show("You have not specified Code");
    return;
  }

After that "**You have not specified Code**" is gone but now its giving Alert of "**"You have specified duplicate value.\nPlease change Duplicate Value**.""

else {
    this.dgSetupList.selectedIndex = (this.bNewRecord ? -1 : this.dgSetupList.selectedIndex) >> 0;
    if (this.com_dbz_modules_components_dbzSetupList_strServerMessage.indexOf("ORA-00001: unique constraint") >= 0)
      mx.controls.Alert.show("You have specified duplicate value.\nPlease change Duplicate Value.");

**Comment by pashminakazi** [comment] 2019-12-05 08:22
I am Unable to solve this Problem.
If you have time to check this Issue then tell me.
I will change both files (MaskedTextInput and dbzSetupList) on VDI as well.

Thanks.

**Comment by pashminakazi** [comment] 2019-12-05 09:25
![Code field in Royale Setuplist](https://user-images.githubusercontent.com/42200979/70221869-ed188200-176a-11ea-9dd6-d510a3abae2e.gif)

**Comment by aharui** [comment] 2019-12-05 20:08
On the VDI, I still could not type into the Code field.  However, using the debugger, I forced the Code field to have a unique ID by putting a breakpoint in AuthorizedPerson_fn_Validate and altering the setupCode.text.  Then I was able to create two new entries without a problem.

I'm not sure what configuration you tested, but one possibility is that there is a focusOut handler on the Code field that will call balanceCode so there is a chance that when you ran your tests, balanceCode was called as you hit the Save button as the Code field lost focus, causing the rest of the logic to use a blank code, which could result in the Alert you saw now that you have bypassed the blank code check.

It seems strange that you cannot debug a Flex version of your code.  You only need to recompile this one module and maybe dbzSetupList.  I can understand that you made the production version hard to debug, but you should have a way to debug individual modules.

Also, it is strange that you are changing the code from the Flex version.  You shouldn't have to do that.  I suspect that balanceCode is somehow not doing the same thing between Flex and Royale.
I will look into that more later after going through your other issues from today.

**Comment by aharui** [comment] 2019-12-06 02:14
It turns out that balanceCode is working with "____" on a New entry.  MaskedTextInput.fullText returns that, but balanceCode processes that into "" and the server apparently thinks that is a duplicate.

I don't see any code that would generate a new unique code, but I also don't see any code that would get a new code back from the server either, so I suspect that the user is supposed to fill in a code for validation.  balanceCode looks like it will help make the user-entered code valid.

I can't type in a new code on the VDI.  The MaskedTextInput is not allowing it.  I'm investigating why.

**Comment by aharui** [comment] 2019-12-06 05:58
OK, I found that mx TextInput wasn't sending out 'textInput' events that MaskedTextInput needed.  That looks like it will affect the code entered being passed to the server.

**Comment by aharui** [comment] 2019-12-09 18:50
Until the repo is restored on the VDI, I cannot test or further investigate this issue, so closing for now.

**Closed by aharui** 2019-12-09 18:50 UTC
Labels: help wanted
