### ISSUE TITLE
selection on advancedDataGrid rows get disabled some time randomly.

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#575] opened 2019-11-19 12:10 UTC
No error on console or debug mode.
no exception has occur.

![advanceddatagridrowselection](https://user-images.githubusercontent.com/36731338/69145445-7bf68080-0a82-11ea-85c5-34536fbba86a.gif)

**Comment by piotrzarzycki21** [comment] 2019-11-19 12:26
@yishayw can it be related at any point to that commit https://github.com/apache/royale-asjs/commit/bc324500cc1a8059ae8b3bfb2b8c8796ca74a15c ?

**Comment by yishayw** [comment] 2019-11-19 19:15
@piotrzarzycki21 , I don't think so, I don't see any references to ItemClickedEvent.multipleSelection in mx. @alinakazi , is this something new? Is it easy to reproduce?

**Comment by alinakazi** [comment] 2019-11-20 09:58
System automatically adds these two elements in advanceddatagrid 
https://paste.apache.org/beo44

so we are unable to select initial 5 to 6 rows in advanceddatagrid

**Comment by aharui** [comment] 2019-11-21 09:13
Should be a duplicate of #564

**Comment by pashminakazi** [comment] 2019-11-21 10:28
@aharui this issue is not duplicate of #564
its not highlighting even its not selecting ADG row in some cases before and after this fix

**Comment by aharui** [comment] 2019-11-21 18:37
Please provide more detail on how to reproduce the problem.  I do not know how to get to the screen in the image provided, and I don't think the current build.xml is building those screens.

**Comment by alinakazi** [comment] 2019-11-21 18:52
Issue exist in every setup. You can see any setup like dbzProductGroup 
Go to Setups - Product -Groups from Menu

**Comment by aharui** [comment] 2019-11-21 18:54
The current build.xml doesn't seem to be building any of these setups.  I keep getting 404 errors.

**Comment by alinakazi** [comment] 2019-11-21 18:55
Go to left grid and  inspect it in debug mode u will see these extra elements overlapping the grid.
https://paste.apache.org/beo44
That's why first five rows are not selectable

**Comment by aharui** [comment] 2019-11-21 18:57
After the changes from yesterday, the elements should have different attributes. But again, I cannot debug because those setups are not being built on the VDI.

**Comment by alinakazi** [comment] 2019-11-21 18:59
go to tax type setup in feasibility module it will not give you 404 error

**Comment by alinakazi** [comment] 2019-11-21 19:00
Uncomment dbzProductGroup Setup  and check it from the menu if you can after relaunching the server
In menu it is in Setup- Product-Groups

**Comment by aharui** [comment] 2019-11-21 19:13
Still not working.  The app seems to be trying to load com/shm/modules instead of com/dbz/modules.

**Comment by aharui** [comment] 2019-11-21 19:40
I altered the URL in the debugger and was able to load Product Groups and all of the rows highlight properly.

**Closed by aharui** 2019-11-21 19:40 UTC

**Comment by alinakazi** [comment] 2019-11-22 10:05
@aharui  
do not see files at path
D:\DBIZSOL\Main\Royale\bin\js-debug
because It only show files that are build last time (due to clean and build the folder again)

if you want to see any setup output file,then look the file here : 
D:\DBIZSOL\Main\Java\web

**Comment by aharui** [comment] 2019-11-22 17:45
The problem is that if old modules are not rebuilt, there could be stale code in Java\web that does not get updated.

And that still doesn't really explain why the code is looking for "shm" instead of "dbz" in some paths.

So, IMO, it is not a good practice to only have portions of the files overwritten during the build.

-Alex
