### ISSUE TITLE
Width Problem - Label in a ScrollableGrid

### ISSUE THREAD

**Issue by Bilbosax** [apache/royale-asjs#1073] opened 2021-02-03 05:27 UTC
I have created an app that is responsive, using the ResponsiveView much like it is used in Tour De Jewel. One of the Components that I put inside of the ResponsiveView contains a ScrollableGrid.  The ScrollableGrid contains a lot of components like sliders, textinputs, checkboxes, and labels.  I set it up to use a BasicLayout so I can put the components wherever I need within the ScrollableGrid, and I have to place them manually by calculating widths of components.  Tracing out width data from the various components shows that the Labels width is the same as the ScrollableGrid container that they are placed into, meaning that they are set to 100% of the width.  I don't want this, I need the Label to be only the width of the visible text.  A label set next to a textInput will actually cover the textInput so that I can't enter text into the component.  Is this a bug with the Label or ScrollableGrid, or is it an effect of being inside of ResponsiveView?  I need some sort of alternative where I can place Labels where I need them without causing scrollbars to appear and without them being so wide that they cover other components.  Here is the basic structure where I am seeing the problem.  In this example, which is in a component that is placed in the ResponsiveView, the Label "stateLabel" traces the same width as the ScrollableGrid "middle" even though it only has 5 letter in the text.

```
    <j:ScrollableGrid localId="middle">
        <j:beads>
            <j:BasicLayout/>
        </j:beads>

        <j:Label localId="stateLabel" text="State"/>
                
    </j:ScrollableGrid>
```

**Comment by carlosrovira** [comment] 2021-02-04 13:17
Hi, I think the problem is that `Grid` and `ScrollableGrid` are 100% width by default. The objective of both containers is to manage the inner content in a responsive way. But inside you must add one or more `GridCell`containers to segment the space in columns. Then in each column/cell you can add more containers (Card? HGroup?...) or other components and controls (Button, Label, TextInput,...) that will be sized in the right way.

HTH

**Comment by Bilbosax** [comment] 2021-02-04 17:23
Well don't I feel dumb.  I would have sworn when I was autocompleteing that component that it said "ScrollableGroup", not ScrollableGrid. Instead, I used a regular Group container with a ScrollingViewport bead, and got exactly what I was looking for.

Apologies.

**Comment by carlosrovira** [comment] 2021-02-04 17:30
ok don't worry, if you feel is all ok you can close this ticket :)

**Closed** 2021-02-04 18:42 UTC
